baseURL = "https://severinvire.github.io/engineering-log/"
title = "Engineering Log"
theme = "PaperMod"
math = true

[params]
  disableThemeToggle = false
  hideFooter = false
  ShowReadingTime = false
  ShowWordCount = false
  comments = false
  customcss = ["css/custom.css"]
  [params.math]
    enable = true

[privacy]
  disallow = ["twitter", "youtube", "vimeo", "instagram", "disqus", "googleanalytics"]